### ISSUE TITLE
Mr.Holmes$ python3 MrHolmes.py

### ISSUE THREAD

**Issue by allelive** [Lucksi/Mr.Holmes#2]
ciao o visto il tuo video e o voluto provare il tuo tool ma non parte puoi aiutarmi a risolvere grazie. 

Traceback (most recent call last):
  File "MrHolmes.py", line 6, in <module>
    from Core.Support import Menu
  File "/home/ale/Mr.Holmes/Core/Support/Menu.py", line 9, in <module>
    from Core import Searcher
  File "/home/ale/Mr.Holmes/Core/Searcher.py", line 17, in <module>
    from Core.Support import Banner_Selector as banner
  File "/home/ale/Mr.Holmes/Core/Support/Banner_Selector.py", line 7, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'

**Comment by allelive** [comment]
> ciao o visto il tuo video eo voluto provare il tuo strumento ma non parte puoi aiutarmi a risolvere grazie.
> 
> Traceback (ultima chiamata più recente): File "MrHolmes.py", riga 6, da Core.Support import Menu File "/home/ale/Mr.Holmes/Core/Support/Menu.py", riga 9, da File di ricerca di importazione principale "/home/ale/Mr.Holmes/Core/Searcher.py", riga 17, da Core.Support import Banner_Selector come file banner "/home/ale/Mr.Holmes/Core/Support/Banner_Selector. py", riga 7, in import tkinter ModuleNotFoundError: nessun modulo denominato 'tkinter'

grazie o risolto in pratica errore mio non avevo visto i log che mancava tkinter e non caricava i moduli.. grazie risolto

**Comment by Lucksi** [comment]
Ciao, scusa se rispondo solo adesso, se ci saranno altri problemi fammelo sapere, spero che il tool ti piaccia

**Comment by allelive** [comment]
si e molto carino e poi in italiano per i più pigri hihihi grazie
