### ISSUE TITLE
Error on nethunter in termux 

### ISSUE THREAD

**Issue by G4k3r** [Lucksi/Mr.Holmes#20]
root㉿localhost)-[/home/kali/Mr.Holmes]
└─# python3 MrHolmes.py
Traceback (most recent call last):
  File "/home/kali/Mr.Holmes/MrHolmes.py", line 8, in <module>
    from Core.Support import Menu
  File "/home/kali/Mr.Holmes/Core/Support/Menu.py", line 10, in <module>
    from Core import Searcher
  File "/home/kali/Mr.Holmes/Core/Searcher.py", line 11, in <module>
    from Core.Support import FileTransfer
  File "/home/kali/Mr.Holmes/Core/Support/FileTransfer.py", line 11, in <module>
    import pyqrcode
ModuleNotFoundError: No module named 'pyqrcode'

**Comment by Lucksi** [comment]
Hi,Looks like some modules are missing try to execute this command after you get in the Mr.Holmes folder:
proot -0 pip3 install -r requirements.txt. It should work after that :)

**Comment by A4b7m** [comment]
Eu tô com o mesmo problema
Mesmo com esse comando 
proot -0 pip3 instalo -r requirements.txt. não tá a funcionar.

**Comment by A4b7m** [comment]
![Uploading Screenshot_20230315-200912.png…]()

**Comment by Lucksi** [comment]
That's strange, have you tried to install the proot module alone?
