### ISSUE TITLE
Lot of problem when it search "APPROXIMATE GEOLOCATION"  when searching informations about phone numbers

### ISSUE THREAD

**Issue by Lechatdu17** [Lucksi/Mr.Holmes#26]
Hi, i'm on a mac M1, 8 GB of ram (i don't know if it helps) and when i want to have information about a phone number (only option i tried for the moment) well when it want to find some the "APPROXIMATE GEOLOCATION" it marks me those multiples errors:

 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ninoroulet/Mr.Holmes/MrHolmes.py", line 42, in <module>
    Main.Menu(Mode)
  File "/Users/ninoroulet/Mr.Holmes/MrHolmes.py", line 36, in Menu
    Menu.Main.main(Mode)
  File "/Users/ninoroulet/Mr.Holmes/Core/Support/Menu.py", line 129, in main
    Searcher_phone.Phone_search.searcher(username, Mode)
  File "/Users/ninoroulet/Mr.Holmes/Core/Searcher_phone.py", line 249, in searcher
    Numbers.Phony.Number(num, report, code, Mode, Type, username)
  File "/Users/ninoroulet/Mr.Holmes/Core/Support/Phone/Numbers.py", line 132, in Number
    Phony.Get_GeoLocation(zone, "Lat", "Long", jsonfile, num, Type)
  File "/Users/ninoroulet/Mr.Holmes/Core/Support/Phone/Numbers.py", line 31, in Get_GeoLocation
    url = urllib.request.urlopen(req)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>
zsh: command not found: OR:
zsh: command not found: Execute

i know it's a lot of errors but if you understand all those errors and you manage to solve my problem, i don't know how to thank you

**Comment by Lucksi** [comment]
Hi unfortunatelly i had some experience in the past that had the same issue the mac himself may be a problem. It may block some requests, do the other modules function normally?

**Comment by Lechatdu17** [comment]
Yeah i think the other modules are working fine

**Comment by Lechatdu17** [comment]
I have resolved the problem, if people are in situation like me, do not use Python 3.11 but use 3.9 (and with that you need to install: requests, packaging, pyqrcode, beautifulsoup4, phonenumbers, Homebrew, wkhtmltopdf and pdfkit.)
