### ISSUE TITLE
Java Error: Mr.HOLMES SCAN TERMINATED

### ISSUE THREAD

**Issue by vikassaini-it** [Lucksi/Mr.Holmes#31]
While scanning for my email I am facing an error:

Mr.HOLMES SCAN TERMINATED
<img width="335" alt="Screenshot 2023-10-23 at 3 50 39 PM" src="https://github.com/Lucksi/Mr.Holmes/assets/98798027/b163a5d4-2296-490d-94ec-12badb060144">

**Comment by Lucksi** [comment]
Hello, that is not an error, it's just a notification to inform you that the scan is completed if you press ok the program will continue :)

**Comment by vikassaini-it** [comment]
Thanks @Lucksi

**Comment by vikassaini-it** [comment]
Another error in phone number scan 

Traceback (most recent call last):
  File "MrHolmes.py", line 42, in <module>
    Main.Menu(Mode)
  File "MrHolmes.py", line 36, in Menu
    Menu.Main.main(Mode)
  File "/Users/xxxxx/Documents/prepo/Mr.Holmes-master/Core/Support/Menu.py", line 138, in main
    Searcher_phone.Phone_search.searcher(username, Mode)
  File "/Users/xxxxx/Documents/prepo/Mr.Holmes-master/Core/Searcher_phone.py", line 261, in searcher
    international = Numbers.Phony.Number(num, report, code, Mode, Type, username)
  File "/Users/xxxxx/Documents/prepo/Mr.Holmes-master/Core/Support/Phone/Numbers.py", line 149, in Number
    Phony.Get_GeoLocation(zone, "Lat", "Long", jsonfile, num, Type)
  File "/Users/xxxxx/Documents/prepo/Mr.Holmes-master/Core/Support/Phone/Numbers.py", line 31, in Get_GeoLocation
    url = urllib.request.urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>

**Comment by Lucksi** [comment]
It is a SSL certificate problem, unfortunately I cannot do anything about it :(

**Comment by vikassaini-it** [comment]
Thanks, We can close it.
