### ISSUE TITLE
Default configuration file error

### ISSUE THREAD

**Issue by gillesxr** [Lucksi/Mr.Holmes#35]
Hello,

I installed MrHolmes with default configuration for proxies and useragents.
When I try to launch MrHolmes (`sudo python3 MrHolmes.py`), there is this error message:

Traceback (most recent call last):
  File "/home/hanabi/Documents/Mr.Holmes/MrHolmes.py", line 8, in <module>
    from Core.Support import Menu
  File "/home/hanabi/Documents/Mr.Holmes/Core/Support/Menu.py", line 10, in <module>
    from Core import Searcher
  File "/home/hanabi/Documents/Mr.Holmes/Core/Searcher.py", line 13, in <module>
    from Core.Support import Requests_Search
  File "/home/hanabi/Documents/Mr.Holmes/Core/Support/Requests_Search.py", line 10, in <module>
    from Core.Support import Headers
  File "/home/hanabi/Documents/Mr.Holmes/Core/Support/Headers.py", line 6, in <module>
    from Core.Support import Useragent
  File "/home/hanabi/Documents/Mr.Holmes/Core/Support/Useragent.py", line 10, in <module>
    class Select:
  File "/home/hanabi/Documents/Mr.Holmes/Core/Support/Useragent.py", line 16, in Select
    f = open(useragent_file, "r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

In the configuration file, we have this:

`proxy_list = Useragents/Useragent.txt`
`useragent_list =` 

I modified the configuration file and it fixes the problem:

`proxy_list = Proxies/Proxy_list.txt`
`useragent_list = Useragents/Useragent.txt`

Best regards,
gillesxr.

**Comment by Lucksi** [comment]
Hello, thank you very much for having shared this problem. 
This was a misspelling on the installation file and I will fix it .

Best regards and have a nice day,
Lucksi.
